---

common:
  #k8s
  k8s_master_uri: https://master.web-staging.os-n3.hw:6443
  k8s_token: "{{ env='K8S_TOKEN' }}"
  k8s_ca_base64: "{{ env='K8S_CA_BASE64' }}"
  k8s_namespace: io
  image_version: "{{ env='IMAGE_VERSION' }}"
  swift_password_env: "{{ env='SWIFT_PASSWORD_B64' }}"

prometheus-swift-bucket-exporter:
  kubectl:
  - template: deployment.yaml.j2
  - template: secret.yaml.j2

testing-prometheus-swift-bucket-exporter:
  k8s_master_uri: https://master.web-testing.os-n3.hw:6443
  k8s_token: "{{ env='K8S_TOKEN_TESTING' }}"
  k8s_namespace: io
  k8s_ca_base64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lKQVBLN29XYXBNaVBaTUEwR0NTcUdTSWIzRFFFQkN3VUFNQll4RkRBU0JnTlYKQkFNTUMwQXhORGt3TXpNd016Z3hNQjRYRFRFM01ETXlOREEwTXprME1Wb1hEVEkzTURNeU1qQTBNemswTVZvdwpGakVVTUJJR0ExVUVBd3dMUURFME9UQXpNekF6T0RFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFEbFBqS1JPVDBoRXVxRkVEQVdFOC9SZ0tya084RGlITjNPNWhDZ2lqN2lCaHpvNDZ0aWFsVWQKR3ppWlhoMkRVVFlrekNEdVVOWmphQk9VZWU5aml0OVN2YnhGM2gzcGlBa2V2eDVzK25MMENvcmtVZDFJaXJkNAorN0ltejJNTFB4Y3Nieml0RFFlLy9ILzlVenJyVUZFTzRZWVhzbHMyWmdYZmdHeHpDK1FETmFibi9qdVlPNnc5CmFIODZGaGpIanRxT0hoci81cDNMa2JvcjdyaUpPSkpXSEp4UUpzOUlBZ01jRHozZzdSSWR2ZkFDc3FhdFQ5cEkKd2F4dlZQRkFhRkNqN3BPbmZqeWpvWFN3K2k0cWdVT3V0VCtQODBkTXF2Q2p2S0pSTWhWbGZ4WjNDSUxhWGhIYgp2R1FZUUxQWElaTGhiSGF5b3dadVpjVUcrakJlOHRpL0FnTUJBQUdqZ1lVd2dZSXdIUVlEVlIwT0JCWUVGSzZpCjlSSXJjclNIaEdPMHlDNHM1S2FHejFNbk1FWUdBMVVkSXdRL01EMkFGSzZpOVJJcmNyU0hoR08weUM0czVLYUcKejFNbm9ScWtHREFXTVJRd0VnWURWUVFEREF0QU1UUTVNRE16TURNNE1ZSUpBUEs3b1dhcE1pUFpNQXdHQTFVZApFd1FGTUFNQkFmOHdDd1lEVlIwUEJBUURBZ0VHTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCcWpIQVYvS3RHCm54NmdWVzMvMXZEN3dLUUFFYkFJbDlBYlRmMks3K3lNY3BWT2hTNEN1eHlldjZTbFBjNmFPUHc5eWpmZkNia0IKd1h2RjJVZU9Cb2I3RCs1T0pUMERqK1gxZ1RSTDJiOGpkU1J1TDV5LzRSdFBMa1N3ejNZWmJNRk1Ka01WYzIzQQpBdWlzenRIR2tRb1NTV3hBaCtKcitwSmNneEJUNDV5dmJyajRJeUdiY2YvaUd5c0xDYWJvL3cyRUpOQWNtOFplCjJESzB3QnFCR2xFNm02cU84N3pneXI5Ym9jeUZnZVp2dnVpcnQxdWt2aVhYSHF3NFJTcm9iT0ZuU3Z2SXFwYi8KbnFzSlFmOEM4QSs4QkpKL2pFQ1c4ZUt1elZCTG16MHpXUC90L29rTXZtSHByZ092SmIrUFo3cHEzVG53TzhUSQozeHFsYWFneVZzdVMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  kubectl:
  - template: deployment.yaml.j2
  - template: secret.yaml.j2
  - template: service.yaml.j2
